PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS sync_metadata (key TEXT PRIMARY KEY NOT NULL, value TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sync_clients (client_id TEXT PRIMARY KEY NOT NULL, next_sequence INTEGER DEFAULT 1 NOT NULL, last_server_revision INTEGER DEFAULT 0 NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS reading_positions (id TEXT PRIMARY KEY NOT NULL, source TEXT NOT NULL, resource_id TEXT NOT NULL, location TEXT NOT NULL, progress INTEGER DEFAULT 0 NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, deleted_at TEXT);
CREATE UNIQUE INDEX IF NOT EXISTS reading_positions_source_resource ON reading_positions (source, resource_id);
CREATE TABLE IF NOT EXISTS reading_history (id TEXT PRIMARY KEY NOT NULL, source TEXT NOT NULL, resource_id TEXT NOT NULL, location TEXT NOT NULL, read_at TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, deleted_at TEXT);
CREATE INDEX IF NOT EXISTS reading_history_read_at ON reading_history (read_at);
CREATE TABLE IF NOT EXISTS preferences (key TEXT PRIMARY KEY NOT NULL, value TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, deleted_at TEXT);
CREATE TABLE IF NOT EXISTS bookmarks (id TEXT PRIMARY KEY NOT NULL, source TEXT NOT NULL, resource_id TEXT NOT NULL, location TEXT NOT NULL, label TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, deleted_at TEXT);
CREATE INDEX IF NOT EXISTS bookmarks_location ON bookmarks (source, resource_id, location);
CREATE TABLE IF NOT EXISTS notes (id TEXT PRIMARY KEY NOT NULL, source TEXT NOT NULL, resource_id TEXT NOT NULL, location TEXT NOT NULL, content TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, deleted_at TEXT);
CREATE INDEX IF NOT EXISTS notes_location ON notes (source, resource_id, location);
CREATE TABLE IF NOT EXISTS markers (id TEXT PRIMARY KEY NOT NULL, source TEXT NOT NULL, resource_id TEXT NOT NULL, location TEXT NOT NULL, style TEXT NOT NULL, color TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, deleted_at TEXT);
CREATE INDEX IF NOT EXISTS markers_location ON markers (source, resource_id, location);
CREATE TABLE IF NOT EXISTS user_cross_references (id TEXT PRIMARY KEY NOT NULL, from_source TEXT NOT NULL, from_resource_id TEXT NOT NULL, from_location TEXT NOT NULL, to_source TEXT NOT NULL, to_resource_id TEXT NOT NULL, to_location TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, deleted_at TEXT);
CREATE INDEX IF NOT EXISTS user_cross_references_from ON user_cross_references (from_source, from_resource_id, from_location);
CREATE TABLE IF NOT EXISTS collections (id TEXT PRIMARY KEY NOT NULL, name TEXT NOT NULL, description TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, deleted_at TEXT);
CREATE TABLE IF NOT EXISTS collection_members (collection_id TEXT NOT NULL REFERENCES collections(id), member_id TEXT NOT NULL, member_type TEXT NOT NULL, position INTEGER DEFAULT 0 NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, deleted_at TEXT, PRIMARY KEY(collection_id, member_id));
CREATE TABLE IF NOT EXISTS reading_plans (id TEXT PRIMARY KEY NOT NULL, title TEXT NOT NULL, description TEXT, definition TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, deleted_at TEXT);
CREATE TABLE IF NOT EXISTS reading_plan_progress (plan_id TEXT NOT NULL REFERENCES reading_plans(id), step_id TEXT NOT NULL, completed_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, deleted_at TEXT, PRIMARY KEY(plan_id, step_id));
CREATE TABLE IF NOT EXISTS memory_verses (id TEXT PRIMARY KEY NOT NULL, resource_id TEXT NOT NULL, location TEXT NOT NULL, prompt TEXT, next_practice_at TEXT, interval_days INTEGER DEFAULT 0 NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, deleted_at TEXT);
CREATE INDEX IF NOT EXISTS memory_verses_due ON memory_verses (next_practice_at);
CREATE TABLE IF NOT EXISTS practice_history (id TEXT PRIMARY KEY NOT NULL, memory_verse_id TEXT NOT NULL REFERENCES memory_verses(id), rating INTEGER NOT NULL, practiced_at TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, deleted_at TEXT);
CREATE INDEX IF NOT EXISTS practice_history_verse ON practice_history (memory_verse_id, practiced_at);
CREATE TABLE IF NOT EXISTS mutation_journal (mutation_id TEXT PRIMARY KEY NOT NULL, client_id TEXT NOT NULL REFERENCES sync_clients(client_id), sequence INTEGER NOT NULL, schema_version INTEGER NOT NULL, command TEXT NOT NULL, created_at TEXT NOT NULL, status TEXT DEFAULT 'pending' NOT NULL, server_revision INTEGER);
CREATE UNIQUE INDEX IF NOT EXISTS mutation_journal_client_sequence ON mutation_journal (client_id, sequence);
CREATE INDEX IF NOT EXISTS mutation_journal_pending ON mutation_journal (status, client_id, sequence);
CREATE TABLE IF NOT EXISTS server_revisions (revision INTEGER PRIMARY KEY NOT NULL, mutation_id TEXT NOT NULL UNIQUE, envelope TEXT NOT NULL, accepted_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS tombstones (entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, deleted_by_mutation_id TEXT NOT NULL, server_revision INTEGER, deleted_at TEXT NOT NULL, PRIMARY KEY(entity_type, entity_id));
